name: CI

on:
  push:
    branches: [ "poc/mvvm" ]
  pull_request:
    branches: [ "poc/mvvm" ]

jobs:
  build-and-test:
    
    runs-on: macos-12

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build and test
      run: xcodebuild clean build test -project Landmarks.xcodeproj -scheme "LandmarksTests" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
